---
version: '3.7'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./websh_front/public:/var/www:ro"
    ports:
      - "80:80"
    # #204
    # WSL2に移行してから host モードでコンテナを起動するとブラウザからアクセスで
    # きなかったのでコメントアウト
    # network_mode: "host"

  websh_front:
    build: &app-build
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - "./websh_front:/work"
    entrypoint: nimble
    command:
      - build
      - -Y
      - -d:local
      - -d:tag:tag
      - -d:revision:rev

  websh_server:
    build:
      context: websh_server
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - ".:/work"
    environment:
      HOST_PWD: "$PWD/websh_server"
      WEBSH_SHELLGEI_BOT_IMAGE_NAME: "alpine:3"
    entrypoint: ./entrypoint.sh
    ports:
      - "5000:5000"
    network_mode: "host"
