version: '3.7'

services:
  base:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    image: base

  build:
    image: base
    volumes:
      - ".:/work"
      - "./bin:/work/bin"
    working_dir: /work
    entrypoint:
      - nimble
      - build
      - -d:release
      - -Y
    depends_on:
      - base
