version: '3.7'

services:
  server:
    image: jiro4989/websh:latest
    volumes:
      - "./websh_server:/work"
    working_dir: /work
    entrypoint: nimble
    command:
      - build
      - -d:release
      - -Y

  front:
    image: jiro4989/websh:latest
    volumes:
      - "./websh_front:/work"
    working_dir: /work
    entrypoint: nimble
    command:
      - build
      - -Y
