version: '3.7'

services:
  base:
    build: .
    image: github.com/jiro4989/websh/websh_server/base

  build_server:
    image: github.com/jiro4989/websh/websh_server/base
    volumes:
      - "./websh_server:/work"
    working_dir: /work
    entrypoint:
      - nimble
      - build
      - -d:release
      - -Y
    depends_on:
      - base

  build_front:
    image: github.com/jiro4989/websh/websh_server/base
    volumes:
      - "./websh_front:/work"
    working_dir: /work
    entrypoint:
      - nimble
      - build
      - -Y
    depends_on:
      - base
