version: '3'

services:
  proxy:
    image: nginx:1.17
    volumes:
      - "./proxy/conf.d:/etc/nginx/conf.d:ro"
      - "./websh_front/public:/var/www:ro"
    ports:
      - "80:80"
    network_mode: "host"

  shellgeibot_1:
    image: theoldmoon0602/shellgeibot
    container_name: shellgeibot_1
    volumes:
      - "./websh_server/tmp/shellgeibot_1/images:/images"
      - "./websh_server/tmp/shellgeibot_1/media:/media"
      - "./websh_server/tmp/shellgeibot_1/script:/tmp/script"
    entrypoint: "tail -f /dev/null"

  shellgeibot_2:
    image: theoldmoon0602/shellgeibot
    container_name: shellgeibot_2
    volumes:
      - "./websh_server/tmp/shellgeibot_2/images:/images"
      - "./websh_server/tmp/shellgeibot_2/media:/media"
      - "./websh_server/tmp/shellgeibot_2/script:/tmp/script"
    entrypoint: "tail -f /dev/null"

  shellgeibot_3:
    container_name: shellgeibot_3
    image: theoldmoon0602/shellgeibot
    volumes:
      - "./websh_server/tmp/shellgeibot_3/images:/images"
      - "./websh_server/tmp/shellgeibot_3/media:/media"
      - "./websh_server/tmp/shellgeibot_3/script:/tmp/script"
    entrypoint: "tail -f /dev/null"

  shellgeibot_4:
    image: theoldmoon0602/shellgeibot
    container_name: shellgeibot_4
    volumes:
      - "./websh_server/tmp/shellgeibot_4/images:/images"
      - "./websh_server/tmp/shellgeibot_4/media:/media"
      - "./websh_server/tmp/shellgeibot_4/script:/tmp/script"
    entrypoint: "tail -f /dev/null"
