---
version: '3.7'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./websh_front/public:/var/www:ro"
    ports:
      - "80:80"

  websh_front:
    build: &app-build
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - "./websh_front:/work"
    entrypoint: nimble
    command:
      - build
      - -Y
      - -d:local
      - -d:tag:tag
      - -d:revision:rev

  websh_server:
    build:
      context: websh_server
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - ".:/work"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      HOST_PWD: "$PWD/websh_server"
      WEBSH_SHELLGEI_BOT_IMAGE_NAME: "ubuntu:20.04"
    ports:
      - "5000:5000"
