version: '3.7'

services:
  build_server:
    image: jiro4989/websh:latest
    volumes:
      - "./websh_server:/work"
    working_dir: /work
    entrypoint:
      - nimble
      - build
      - -d:release
      - -Y

  build_front:
    image: jiro4989/websh:latest
    volumes:
      - "./websh_front:/work"
    working_dir: /work
    entrypoint:
      - nimble
      - build
      - -Y
