name: deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: application
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: application/websh.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy application
        run: curl ${{ secrets.WEBHOOK_URL }}
