name: test

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pull docker image
        run: docker pull jiro4989/websh:latest
      - name: Test server
        run: docker-compose -f docker-compose-ci.yml run server test -Y
      - name: Build server
        run: docker-compose -f docker-compose-ci.yml run server
      - name: Test API
        run: ./.github/scripts/api_test.sh
      - name: Build front
        run: docker-compose -f docker-compose-ci.yml run front
      - name: automerge
        uses: "pascalgn/automerge-action@v0.7.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
