name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull docker image
      run: docker pull jiro4989/websh:latest
    - name: Build
      run: docker-compose -f docker-compose-ci.yml up
    - name: Archive release files
      run: |
        mkdir -p dist/websh
        cp -r websh_server/bin dist/websh
        cp -r websh_front/public dist/websh
        pushd dist
        tar czf websh.tar.gz websh
        popd
        ls -lah dist/websh.tar.gz
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/websh.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy application
      run: curl ${{ secrets.WEBHOOK_URL }}
      if: startsWith(github.ref, 'refs/tags/')
