name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache ubuntu image
      id: cache-ubuntu-image
      uses: actions/cache@v1
      with:
        path: ~/docker-cache
        key: ${{ runner.os }}-docker-ubuntu-${{ hashFiles('**/Dockerfile') }}
    - name: Load docker image
      if: steps.cache-ubuntu-image.outputs.cache-hit == 'true'
      run: |
        gunzip ~/docker-cache/ubuntu.gz
        docker load -i ~/docker-cache/ubuntu
    - name: Pull docker image
      run: docker pull jiro4989/websh:latest
    - name: Build
      run: docker-compose -f docker-compose-ci.yml up
    - name: Archive release files
      run: |
        mkdir -p dist/websh
        cp -r websh_server/bin dist/websh
        cp -r websh_front/public dist/websh
        pushd dist
        tar czf websh.tar.gz websh
        popd
        ls -lah dist/websh.tar.gz
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/websh.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Save docker ubuntu image to cache directory
      run: |
        mkdir -p ~/docker-cache
        docker save ubuntu:18.04 | gzip -c > ~/docker-cache/ubuntu.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy application
      uses: joelwmale/webhook-action@master
      if: startsWith(github.ref, 'refs/tags/')
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: "Hello from github actions!"
