name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - '*/README.*'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - '*/README.*'
      - 'docs/*'

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "no [skip ci]"

  test-build-image:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build

  test-front:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          pushd websh_server
          echo -e '\nswitch("d", "ci")' > tests/config.nims
      - name: Test
        run: docker-compose run --rm websh_front

  test-server:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          pushd websh_server
          echo -e '\nswitch("d", "ci")' > tests/config.nims
      - name: Build image (base)
        run: docker build --target base -t base .
      - name: Test (server)
        run: docker run --rm -v $PWD/websh_server:/work -t base nimble test -Y
